### ISSUE TITLE
change axes (residue indices)

### ISSUE THREAD

**Issue by DDGmichigan** [tekpinar/correlationplus#18]
Hello!
I am currently using correlationplus to analyze residue based ndcc matrices on a dimer.
I want to change the residue indices spacing to like 0 10 20 30 40 50...all the way to 550
However I am not sure how I can achieve that
correlationplus visualize -h does not give me any options to play with the scale of the residue axis.

Thanks in advance
![7ALI_acetonitrile_all_data png-overall](https://user-images.githubusercontent.com/48214273/143938050-b6b17164-ee3f-46ab-bb37-92e7df4b6485.png)

**Comment by tekpinar** [comment]
Unfortunately, you can not do it directly from the script interface. Here are two options that may help:
1) Use the ndcc matrix data file and call cmap_discretize(cmap, N) to obtain the same discrete color map directly in your custom script that you use matplotlib. 
2) Modify or override  overallCorrelationMap() function. Particularly, comment lines 467 to 492 except major_nums and major_labels. Fill these lists according to your needs.
