### ISSUE TITLE
color scale for pml

### ISSUE THREAD

**Issue by rupeshagarwal** [tekpinar/correlationplus#20]
What is the color scale for the pymol (pml) files? and what are red/orange spheres?

**Comment by tekpinar** [comment]
Hi,
In fact, I don't define a color scale in pml file. It is the default color scale of Pymol (probably blue-white-red: blue is the lowest and red is the highest). You can change the colors in Pymol according to your taste as explained here: 
https://pymolwiki.org/index.php/Spectrum

What are the red/orange spheres: I highlight the top 10% residues with the highest value (of betweenness, degree etc.) as spheres.

**Comment by rupeshagarwal** [comment]
Thanks! :)
